apiVersion: v1
kind: Service
metadata:
  name: wine-classifier-service
  namespace: wine-classifier
  labels:
    app: wine-classifier
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: wine-classifier
